//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjectCom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public Blog()
        {
            this.BlogContributers = new HashSet<BlogContributer>();
            this.Posts = new HashSet<Post>();
        }
    
        public int BlogID { get; set; }
        public string BlogTitle { get; set; }
        public string BlogDescription { get; set; }
        public System.DateTime BlogCreateDate { get; set; }
        public bool BlogIsBlocked { get; set; }
        public bool BlogIsActive { get; set; }
        public string BlogHeaderPhoto { get; set; }
        public int FKUserID { get; set; }
    
        public virtual ICollection<BlogContributer> BlogContributers { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}
