//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjectCom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string CommentBody { get; set; }
        public System.DateTime CommentCreateDate { get; set; }
        public bool CommentIsBlocked { get; set; }
        public bool CommentIsActive { get; set; }
        public int FKPostID { get; set; }
        public int FKUserID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
