//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjectCom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int PostID { get; set; }
        public string PostTitle { get; set; }
        public string PostBody { get; set; }
        public System.DateTime PostCreateDate { get; set; }
        public bool PostIsBlocked { get; set; }
        public bool PostIsActive { get; set; }
        public string PostKeyWords { get; set; }
        public bool PostIsPublished { get; set; }
        public int FKBlogID { get; set; }
        public int FKUserID { get; set; }
        public Nullable<bool> IsCommentable { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
    }
}
