//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjectCom
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Blogs = new HashSet<Blog>();
            this.Comments = new HashSet<Comment>();
            this.Posts = new HashSet<Post>();
            this.BlogContributers = new HashSet<BlogContributer>();
        }
    
        public int UserID { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserNickName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public bool UserIsBlocked { get; set; }
        public string UserPhoto { get; set; }
        public int FKRoleID { get; set; }

        public virtual ICollection<Blog> Blogs { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<BlogContributer> BlogContributers { get; set; }
    }
}
